os.system("pip install -r requirements.txt")
os.system("npm i net")
os.system("npm i http2")
os.system("npm i request")
os.system("npm i tls")
os.system("npm i cluster")
os.system("npm i url")
os.system("npm i crypto")
os.system("npm i fs")
os.system("npm i cloudscraper")
os.system("npm i randomstring")
os.syste("python p.py")
