{
    presets: "4", # Sets the presets file | '?' for asking | 'n' for sites.txt | '1' for http/s | '2' for socks4 | '3' for socks5 | '4' for all

    removeWebsites: "y", # Removes not connectable websites | '?' for asking | 'y' or 'n'

    removeProxyless: "y", # Removes websites if no proxies are found | '?' for asking | 'y' or 'n'

    randomUseragent: "y", # Decides if random useragent is used | '?' for asking | 'y' for random useragent | 'n' will use the most common useragent

    threads: "9", # '?' for asking | '[Threadcount]'

    timeout: "10", # Sets timeout for the sites | '?' for asking | '[seconds]' | '10' is default

    proxyDelimiter: ":" # Set custom Delimiter for proxies (proxy[DELIMITER]port). | '?' for asking | ':' is default | Regex can be used
}